name: Scanner de Doble S Studio
on: workflow_dispatch

jobs:
  run_scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar herramientas
        run: pip install requests
      - name: Ejecutar Auditoría
        run: python scanner.py
