name: Scanner Doble S
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - setup-python:
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install
        run: pip install requests pandas
      - name: Run
        run: python main.py
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Prospectos-Doble-S
          path: lista_prospectos.csv
